version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/go:1.15.8

jobs:
  make_lib:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libboost-all-dev
      - run: sudo apt-get install libtbb-dev
      - run: cd arbitrator && make -f makefile_linux
      - store_artifacts:
          path: arbitrator/liburlarbitrator.so
      # - persist_to_workspace:
      #     root: arbitrator
      #     paths:
      #       - libarbitrator.so
      
  # test:
  #   executor: my-executor
  #   steps:
  #     - checkout
  #     - run: sudo apt-get update
  #     - run: sudo apt-get install libboost-all-dev
  #     - run: sudo apt-get install libtbb-dev
  #     - attach_workspace:
  #         at: arbitrator
      - run: go env -w GOPRIVATE=github.com/arcology-network
      - run: ls
      - run: ls -l arbitrator
      - run: sudo ln -s /home/circleci/project/arbitrator/liburlarbitrator.so /usr/local/lib
      - run: sudo ls -l /usr/local/lib
      - run: go build ./...
      - run: export LD_LIBRARY_PATH=/usr/local/lib && go test -v ./...

workflows:
  version: 2
  make_lib_and_test:
    jobs:
      - make_lib
      # - test:
      #     requires:
      #       - make_lib
